import type { CaseResult, ProviderId } from "../../core/types.js";
import { formatMs, formatUsage } from "./ui";

export function CaseDetail({ result, provider }: { result: CaseResult; provider: ProviderId }) {
  return (
    <div className="case-detail">
      {result.error ? (
        <div className="detail-block">
          <h4>Error</h4>
          <p className="error-text">{result.error}</p>
        </div>
      ) : null}

      {result.assertions.length > 0 ? (
        <div className="detail-block">
          <h4>Assertions</h4>
          <ul className="assertion-list">
            {result.assertions.map((a, i) => (
              <li key={i} className={a.passed ? "ok" : "bad"}>
                <span className="assertion-icon" aria-label={a.passed ? "passed" : "failed"}>
                  {a.passed ? "✓" : "✗"}
                </span>
                <span>{a.message.replace(/^(Passed|Failed): /, "")}</span>
              </li>
            ))}
          </ul>
        </div>
      ) : null}

      {result.output !== undefined ? (
        <div className="detail-block">
          <h4>
            Output{" "}
            {provider === "mock" ? <span className="tag">mock fixture — not generated by a model</span> : null}
            {result.stopReason && provider !== "mock" ? <span className="tag">stop: {result.stopReason}</span> : null}
          </h4>
          <pre className="code">{result.output || <em className="muted">(empty response)</em>}</pre>
        </div>
      ) : null}

      {result.rendered ? (
        <details className="detail-block">
          <summary>Rendered prompt</summary>
          {result.rendered.system ? (
            <>
              <div className="code-label">System</div>
              <pre className="code">{result.rendered.system}</pre>
            </>
          ) : null}
          <div className="code-label">User</div>
          <pre className="code">{result.rendered.user}</pre>
        </details>
      ) : null}

      <dl className="detail-meta">
        <div>
          <dt>Latency</dt>
          <dd>{formatMs(result.latencyMs)}</dd>
        </div>
        <div>
          <dt>Tokens</dt>
          <dd>{result.usage ? formatUsage(result.usage) : "not reported"}</dd>
        </div>
        {result.model ? (
          <div>
            <dt>Model</dt>
            <dd>{result.model}</dd>
          </div>
        ) : null}
      </dl>
    </div>
  );
}
