import type { CaseResult, ProviderId } from "../../core/types.js";
import { Icon } from "./Icon";
import { formatMs, formatUsage } from "./ui";

export function CaseDetail({ result, provider }: { result: CaseResult; provider: ProviderId }) {
  return (
    <div className="case-detail">
      {result.error ? (
        <div className="detail-error">
          <Icon name="alert" />
          <div>
            <div className="detail-label">Error</div>
            <p>{result.error}</p>
          </div>
        </div>
      ) : null}

      {result.assertions.length > 0 ? (
        <section>
          <h4 className="detail-label">Assertions</h4>
          <ul className="assertion-list">
            {result.assertions.map((a, i) => (
              <li key={i} className={a.passed ? "is-pass" : "is-fail"}>
                <span className="assertion-mark" aria-label={a.passed ? "passed" : "failed"} role="img">
                  <Icon name={a.passed ? "check" : "x"} />
                </span>
                <span className="assertion-text">{a.message.replace(/^(Passed|Failed): /, "")}</span>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      {result.output !== undefined ? (
        <section>
          <h4 className="detail-label">
            Output
            {provider === "mock" ? <span className="tag">Mock fixture · not generated by a model</span> : null}
            {result.stopReason && provider !== "mock" ? <span className="tag">stop: {result.stopReason}</span> : null}
          </h4>
          <pre className="code-block">{result.output || <em className="muted">(empty response)</em>}</pre>
        </section>
      ) : null}

      {result.rendered ? (
        <details className="disclosure">
          <summary>
            <Icon name="chevronRight" className="disclosure-chevron" />
            Rendered prompt
          </summary>
          <div className="disclosure-body">
            {result.rendered.system ? (
              <>
                <div className="code-caption">System</div>
                <pre className="code-block">{result.rendered.system}</pre>
              </>
            ) : null}
            <div className="code-caption">User</div>
            <pre className="code-block">{result.rendered.user}</pre>
          </div>
        </details>
      ) : null}

      <dl className="detail-meta">
        <div>
          <dt>Latency</dt>
          <dd>{formatMs(result.latencyMs)}</dd>
        </div>
        <div>
          <dt>Tokens</dt>
          <dd>{result.usage ? formatUsage(result.usage) : "Not reported"}</dd>
        </div>
        {result.model ? (
          <div>
            <dt>Model</dt>
            <dd className="mono">{result.model}</dd>
          </div>
        ) : null}
      </dl>
    </div>
  );
}
